config/routes.rb
Rails.application.routes.draw do
  
  
  root 'pages#homepage'
  get 'pages/about', to: 'pages#about'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def homepage
    
  end
  
  def background_image_tag
  end
  
  
  def about
    
  end 
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE, html>
<html>
 <h1 title="They've got sass" style="color:turquoise;"> <center>What About Them</center></h1>

<center> <%= image_tag 'GreatWaveOffKanagawa.jpg' %> </center> 


<br>

<p1> <center>Eighty percent of the sea wolf's diet is seafood. Catch more fish. Eat more fish, bitches. </center></p1>

<br>

<center><%= link_to 'Homepage', root_path %></center>
</html>

app/views/pages/homepage.html.erb
<!DOCTYPE, html>
<html>
  
<h1 title="Especially from you" style="color:turquoise;"> <center>Sea Wolves: Taking no Shit</center> </h1>
<p1> <center> The Sea Wolves of British Columbia take their home in the sea and on the land.</center> </p1>

<center><%= image_tag('sea_wolf.jpg', style: "height: 100%; width: 100%") %></center>

<br>
<center><%= link_to 'About', pages_about_path %></center>
<br>



</html>